/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel_management_system;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.time.Duration;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author ayamo
 */
public class CheckOutForm extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form CheckOutForm
     */
    CalCost calctotal = new CalCost();
    String CheckMethod = "cash";
    String currentDate = String.valueOf(java.time.LocalDate.now());
    double price;
    String boardType, checkIn;
    connect_database conn = null;

    public CheckOutForm() {
        initComponents();
        jComboBox1.removeAllItems();
        try {
            conn = connect_database.getInstance();
            ResultSet rs = conn.getS().executeQuery("select * from residents where Status = 'Check In'");
            while (rs.next()) {
                System.out.println("id: " + rs.getString("residentID"));
                jComboBox1.addItem(rs.getString("residentID"));
            }
        } catch (Exception e) {
        }
        jComboBox1.addActionListener(this);

        checkOutTime.setText(currentDate);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        password2 = new javax.swing.JLabel();
        CancelBtn2 = new javax.swing.JButton();
        checkOutBtn = new javax.swing.JButton();
        checkInTime = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cashRB = new javax.swing.JRadioButton();
        payPalRB = new javax.swing.JRadioButton();
        creditCardRB = new javax.swing.JRadioButton();
        roomNumTF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        checkOutTime = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(200, 30));
        setMinimumSize(new java.awt.Dimension(1000, 640));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0,120));

        jLabel6.setFont(new java.awt.Font("Andalus", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Check Out");

        jLabel7.setFont(new java.awt.Font("Andalus", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Resident ID:");

        password2.setFont(new java.awt.Font("Andalus", 1, 20)); // NOI18N
        password2.setForeground(new java.awt.Color(255, 255, 255));
        password2.setText("Room Number:");

        CancelBtn2.setBackground(new java.awt.Color(24, 130, 203));
        CancelBtn2.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        CancelBtn2.setForeground(new java.awt.Color(255, 255, 255));
        CancelBtn2.setText("Cancel");
        CancelBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelBtn2MouseClicked(evt);
            }
        });
        CancelBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtn2ActionPerformed(evt);
            }
        });

        checkOutBtn.setBackground(new java.awt.Color(24, 130, 203));
        checkOutBtn.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        checkOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        checkOutBtn.setText("Check Out");
        checkOutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkOutBtnMouseClicked(evt);
            }
        });
        checkOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutBtnActionPerformed(evt);
            }
        });

        checkInTime.setFont(new java.awt.Font("Andalus", 1, 20)); // NOI18N
        checkInTime.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Andalus", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CheckIn Time:");

        jLabel13.setFont(new java.awt.Font("Andalus", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Payment Method:");

        cashRB.setBackground(new java.awt.Color(248, 248, 255));
        buttonGroup1.add(cashRB);
        cashRB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cashRB.setForeground(new java.awt.Color(24, 130, 203));
        cashRB.setText("Cash");
        cashRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashRBActionPerformed(evt);
            }
        });

        payPalRB.setBackground(new java.awt.Color(248, 248, 255));
        buttonGroup1.add(payPalRB);
        payPalRB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        payPalRB.setForeground(new java.awt.Color(24, 130, 203));
        payPalRB.setText("PayPal");
        payPalRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payPalRBActionPerformed(evt);
            }
        });

        creditCardRB.setBackground(new java.awt.Color(248, 248, 255));
        buttonGroup1.add(creditCardRB);
        creditCardRB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        creditCardRB.setForeground(new java.awt.Color(24, 130, 203));
        creditCardRB.setText("Credit Card");
        creditCardRB.setMaximumSize(new java.awt.Dimension(120, 24));
        creditCardRB.setMinimumSize(new java.awt.Dimension(120, 24));
        creditCardRB.setPreferredSize(new java.awt.Dimension(120, 24));
        creditCardRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditCardRBActionPerformed(evt);
            }
        });

        roomNumTF.setBackground(new java.awt.Color(248, 248, 255));
        roomNumTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        roomNumTF.setForeground(new java.awt.Color(24, 130, 203));

        jLabel14.setFont(new java.awt.Font("Andalus", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CheckOut Time:");

        checkOutTime.setFont(new java.awt.Font("Andalus", 1, 20)); // NOI18N
        checkOutTime.setForeground(new java.awt.Color(255, 255, 255));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(password2, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(cashRB, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(payPalRB, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(creditCardRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(roomNumTF)
                                    .addComponent(checkInTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkOutTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(checkOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CancelBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(16, 16, 16)
                                        .addComponent(roomNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(password2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(checkInTime, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(checkOutTime, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashRB)
                    .addComponent(payPalRB)
                    .addComponent(creditCardRB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 670, 530));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_out.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelBtn2MouseClicked

        new AdminDashboardForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_CancelBtn2MouseClicked

    private void CancelBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtn2ActionPerformed

        new ReceptionForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_CancelBtn2ActionPerformed

    private void checkOutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkOutBtnMouseClicked


    }//GEN-LAST:event_checkOutBtnMouseClicked

    private void creditCardRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditCardRBActionPerformed
        CheckMethod = "creditCard";
    }//GEN-LAST:event_creditCardRBActionPerformed

    private void checkOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutBtnActionPerformed
        String id = jComboBox1.getSelectedItem().toString();
        String s1 = roomNumTF.getText();
        FacadeCheckout facade = new FacadeCheckout(calctotal);
        facade.CheckOutUsingFacade(id, s1, CheckMethod);

    }//GEN-LAST:event_checkOutBtnActionPerformed

    private void cashRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashRBActionPerformed
        CheckMethod = "cash";
    }//GEN-LAST:event_cashRBActionPerformed

    private void payPalRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payPalRBActionPerformed
        CheckMethod = "payPal";
    }//GEN-LAST:event_payPalRBActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        System.out.println("hotel_management_system.CheckOutForm.jComboBox1ActionPerformed()");
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOutForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cashRB;
    private javax.swing.JLabel checkInTime;
    private javax.swing.JButton checkOutBtn;
    private javax.swing.JLabel checkOutTime;
    private javax.swing.JRadioButton creditCardRB;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel password2;
    private javax.swing.JRadioButton payPalRB;
    private javax.swing.JTextField roomNumTF;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        try {
            connect_database conn = connect_database.getInstance();

            int number = Integer.parseInt(jComboBox1.getSelectedItem().toString());

            ResultSet rs = conn.getS().executeQuery("SELECT * FROM residents where residentID ='" + jComboBox1.getSelectedItem().toString() + "'");
            System.out.println("id: " + number);

            while (rs.next()) {
                System.out.println("e: " + rs.getString("RoomNumber"));

                roomNumTF.setText(String.valueOf(rs.getString("RoomNumber")));
                checkInTime.setText(String.valueOf(rs.getString("Date")));
                price = Double.parseDouble(rs.getString("totalCost"));
                System.out.println("price" + price);
                boardType = rs.getString("Boardingtype");
                System.out.println("Boardingtype: " + boardType);
            }

            System.out.println("price: " + price);

            LocalDate d1 = LocalDate.parse(checkInTime.getText(), DateTimeFormatter.ISO_LOCAL_DATE);
            LocalDate d2 = LocalDate.parse(currentDate, DateTimeFormatter.ISO_LOCAL_DATE);
            Duration diff = Duration.between(d1.atStartOfDay(), d2.atStartOfDay());
            long diffDays = diff.toDays();

            System.out.println("time: " + diffDays);

            if (boardType.equals("Full Board")) {
                CalculatePrice c1 = new CalculatePrice(750 * diffDays);
                calctotal.addBoarding(c1);
            } else if (boardType.equals("Half Board")) {
                CalculatePrice c1 = new CalculatePrice(500 * diffDays);
                calctotal.addBoarding(c1);
            } else if (boardType.equals("Bed And Breakfast")) {
                CalculatePrice c1 = new CalculatePrice(250 * diffDays);
                calctotal.addBoarding(c1);
            }

            CalculatePrice c2 = new CalculatePrice(price * diffDays);
            calctotal.addRoom(c2);

        } catch (Exception ee) {
        }
        // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
