/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel_management_system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author ayamo
 */
public class IncomeForm extends javax.swing.JFrame {

    /**
     * Creates new form IncomeForm
     */
    public IncomeForm() {
        initComponents();
       
          CountCustomers();
          
    }
    Statement St = null , St1 = null ;
    Connection con = null;
    PreparedStatement Pst = null;
    ResultSet Rs = null , Rs1 = null;
    private void CountCustomers(){
        try {
            St = con.createStatement();
            Rs =  St.executeQuery("select Count (*) from Customer");
            Rs.next();
            label2.setText(""+Rs.getString(1));
        } catch (Exception e) {
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        startDateTF = new javax.swing.JTextField();
        CancelBtn = new javax.swing.JButton();
        SearchBtn = new javax.swing.JButton();
        endDateTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        icomeCB = new javax.swing.JComboBox<>();
        Lable1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        incomeLable1 = new javax.swing.JLabel();
        customerLable = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(200, 30));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0,120));

        jLabel3.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Start Date:");

        jLabel4.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("End Date:");

        startDateTF.setBackground(new java.awt.Color(248, 248, 255));
        startDateTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        startDateTF.setForeground(new java.awt.Color(72, 138, 199));

        CancelBtn.setBackground(new java.awt.Color(72, 138, 199));
        CancelBtn.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        CancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        CancelBtn.setText("Cancel");
        CancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelBtnMouseClicked(evt);
            }
        });
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        SearchBtn.setBackground(new java.awt.Color(72, 138, 199));
        SearchBtn.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        SearchBtn.setForeground(new java.awt.Color(255, 255, 255));
        SearchBtn.setText("Search");
        SearchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchBtnMouseClicked(evt);
            }
        });
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        endDateTF.setBackground(new java.awt.Color(248, 248, 255));
        endDateTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        endDateTF.setForeground(new java.awt.Color(72, 138, 199));

        jLabel5.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Time ");

        icomeCB.setBackground(new java.awt.Color(248, 248, 255));
        icomeCB.setForeground(new java.awt.Color(72, 138, 199));
        icomeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Weekly", "Monthly", "Year" }));
        icomeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icomeCBActionPerformed(evt);
            }
        });

        Lable1.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        Lable1.setForeground(new java.awt.Color(255, 255, 255));
        Lable1.setText("Income:");

        label2.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Customers:");

        incomeLable1.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        incomeLable1.setForeground(new java.awt.Color(255, 255, 255));

        customerLable.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        customerLable.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(customerLable, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Lable1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(endDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(icomeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(startDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12))
                            .addComponent(incomeLable1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icomeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lable1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incomeLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerLable, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 530, 490));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/income.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelBtnMouseClicked

        
         new AdminDashboardForm().setVisible(true);
         dispose();
    }//GEN-LAST:event_CancelBtnMouseClicked

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        
        new AdminDashboardForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void SearchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchBtnMouseClicked

        
    }//GEN-LAST:event_SearchBtnMouseClicked

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        String Startdate = startDateTF.getText(); 
       String enddate  = endDateTF.getText();
       
       try{
           connect_database conn = connect_database.getInstance();
           System.out.println(Startdate);
           System.out.println(enddate);
           
           String Query = "Select * from residents where Date between '"+Startdate+"' and '"+enddate+"'";
           ResultSet rs = conn.getS().executeQuery(Query);
           int counter = 0 ;
           double income = 0.0;
           while(rs.next()){
               income+=  Double.parseDouble( rs.getString("totalCost")); 
             counter++; 
           }
           customerLable.setText(Integer.toString(counter));
           incomeLable1.setText( " $ "+Double.toString(income) );
       }
       catch(Exception ex){
                       JOptionPane.showMessageDialog(null, "Invlid Date Enter valid Date ");

       }
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void icomeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icomeCBActionPerformed
        String Type = icomeCB.getSelectedItem()+"";
         connect_database conn = connect_database.getInstance();
          String Startdate =String.valueOf(java.time.LocalDate.now());
           LocalDate date= LocalDate.parse(Startdate);
  
        if(Type.equals("Weekly")){
            try{
             LocalDate enddate= date.minusDays(7);
                System.out.println(Startdate);
                 System.out.println(enddate);
                
             String Query = "Select * from residents where Date between '"+enddate+"' and '"+Startdate+"'";
           ResultSet rs = conn.getS().executeQuery(Query);
           int counter = 0 ;
           double income = 0.0;
           while(rs.next()){
               income+=  Double.parseDouble( rs.getString("totalCost")); 
             counter++; 
           }
           
            customerLable.setText(Integer.toString(counter));
           incomeLable1.setText( " $ "+Double.toString(income) );
        }
            catch(Exception e){
                  JOptionPane.showMessageDialog(null, "Something Error ... ! ");
                
            }
        }
        
        else if(Type.equals("Monthly")){
        
             try{
             LocalDate enddate= date.minusDays(30);
                System.out.println(Startdate);
                 System.out.println(enddate);
                
             String Query = "Select * from residents where Date between '"+enddate+"' and '"+Startdate+"'";
           ResultSet rs = conn.getS().executeQuery(Query);
           int counter = 0 ;
           double income = 0.0;
           while(rs.next()){
               income+=  Double.parseDouble( rs.getString("totalCost")); 
             counter++; 
           }
           
            customerLable.setText(Integer.toString(counter));
           incomeLable1.setText( " $ "+Double.toString(income) );
        }
            catch(Exception e){
                  JOptionPane.showMessageDialog(null, "Something Error ... ! ");       
            }
            
        }
        else {
             try{
             LocalDate enddate= date.minusDays(365);
                System.out.println(Startdate);
                 System.out.println(enddate);
                
             String Query = "Select * from residents where Date between '"+enddate+"' and '"+Startdate+"'";
           ResultSet rs = conn.getS().executeQuery(Query);
           int counter = 0 ;
           double income = 0.0;
           while(rs.next()){
               income+=  Double.parseDouble( rs.getString("totalCost")); 
             counter++; 
           }
           
           customerLable.setText(Integer.toString(counter));
           incomeLable1.setText( " $ "+Double.toString(income) );
        }
            catch(Exception e){
                  JOptionPane.showMessageDialog(null, "Something Error ... ! ");
                
            }
        }
    }//GEN-LAST:event_icomeCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IncomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IncomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IncomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IncomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IncomeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JLabel Lable1;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JLabel customerLable;
    private javax.swing.JTextField endDateTF;
    private javax.swing.JComboBox<String> icomeCB;
    private javax.swing.JLabel incomeLable1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label2;
    private javax.swing.JTextField startDateTF;
    // End of variables declaration//GEN-END:variables
}
