/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel_management_system;

/**
 *
 * @author ayamo
 */
public class ReceptionForm extends javax.swing.JFrame implements Dashboard{

    /**
     * Creates new form ReceptionForm
     */
    public ReceptionForm() {
        //initComponents();
        Draw_Dashboard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        updateRoombtn = new javax.swing.JButton();
        logOutbtn = new javax.swing.JButton();
        newResidentbtn = new javax.swing.JButton();
        checkOutbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(200, 30));
        setMinimumSize(new java.awt.Dimension(1000, 640));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,120));

        updateRoombtn.setBackground(new java.awt.Color(72, 138, 199));
        updateRoombtn.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        updateRoombtn.setForeground(new java.awt.Color(255, 255, 255));
        updateRoombtn.setText("Update Room Status");
        updateRoombtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateRoombtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateRoombtnMouseClicked(evt);
            }
        });
        updateRoombtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRoombtnActionPerformed(evt);
            }
        });

        logOutbtn.setBackground(new java.awt.Color(72, 138, 199));
        logOutbtn.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        logOutbtn.setForeground(new java.awt.Color(255, 255, 255));
        logOutbtn.setText("Log Out");
        logOutbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutbtnMouseClicked(evt);
            }
        });
        logOutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutbtnActionPerformed(evt);
            }
        });

        newResidentbtn.setBackground(new java.awt.Color(72, 138, 199));
        newResidentbtn.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        newResidentbtn.setForeground(new java.awt.Color(255, 255, 255));
        newResidentbtn.setText("New Resident Form");
        newResidentbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newResidentbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newResidentbtnMouseClicked(evt);
            }
        });
        newResidentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newResidentbtnActionPerformed(evt);
            }
        });

        checkOutbtn.setBackground(new java.awt.Color(72, 138, 199));
        checkOutbtn.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        checkOutbtn.setForeground(new java.awt.Color(255, 255, 255));
        checkOutbtn.setText("Check Out");
        checkOutbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkOutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkOutbtnMouseClicked(evt);
            }
        });
        checkOutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logOutbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(checkOutbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateRoombtn, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                        .addComponent(newResidentbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(newResidentbtn)
                .addGap(33, 33, 33)
                .addComponent(updateRoombtn)
                .addGap(20, 20, 20)
                .addComponent(checkOutbtn)
                .addGap(31, 31, 31)
                .addComponent(logOutbtn)
                .addGap(162, 162, 162))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 480, 530));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/receptionist.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateRoombtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateRoombtnMouseClicked
        try {
            UpdateRoomStatusForm update = new UpdateRoomStatusForm();
            update.setVisible(true);
            dispose();
        } catch (Exception e1) {
            e1.printStackTrace();
        }

    }//GEN-LAST:event_updateRoombtnMouseClicked

    private void logOutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutbtnMouseClicked
       dispose();
    }//GEN-LAST:event_logOutbtnMouseClicked

    private void newResidentbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newResidentbtnMouseClicked
        try {

            ReceptionistsForm custom = new ReceptionistsForm();
            custom.setVisible(true);
            dispose();
        } catch (Exception e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_newResidentbtnMouseClicked

    private void checkOutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkOutbtnMouseClicked
        CheckOutForm check;
        try {
            check = new CheckOutForm();
            check.setVisible(true);
            dispose();
        } catch (Exception e1) {
            e1.printStackTrace();
        }
    
    }//GEN-LAST:event_checkOutbtnMouseClicked

    private void updateRoombtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRoombtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateRoombtnActionPerformed

    private void checkOutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkOutbtnActionPerformed

    private void logOutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutbtnActionPerformed
        
        new LoginPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_logOutbtnActionPerformed

    private void newResidentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newResidentbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newResidentbtnActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptionForm.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptionForm.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptionForm.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptionForm.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceptionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkOutbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logOutbtn;
    private javax.swing.JButton newResidentbtn;
    private javax.swing.JButton updateRoombtn;
    // End of variables declaration//GEN-END:variables

 @Override
    public void Draw_Dashboard() {
        initComponents();
    }
}
